import { AchievementDef } from "@/types/gamification";

export const ACHIEVEMENTS: AchievementDef[] = [
  {
    key: "first_blood",
    name: "First Blood",
    description: "Get your first correct answer",
    iconPath: "/badges/first_blood.svg",
    xpReward: 25,
    rarity: "common",
  },
  {
    key: "on_fire",
    name: "On Fire",
    description: "5 correct answers in a row",
    iconPath: "/badges/on_fire.svg",
    xpReward: 50,
    rarity: "common",
  },
  {
    key: "unstoppable",
    name: "Unstoppable",
    description: "10 correct answers in a row",
    iconPath: "/badges/unstoppable.svg",
    xpReward: 100,
    rarity: "rare",
  },
  {
    key: "speed_demon",
    name: "Speed Demon",
    description: "Answer correctly in under 5 seconds",
    iconPath: "/badges/speed_demon.svg",
    xpReward: 30,
    rarity: "common",
  },
  {
    key: "domain_master_identity",
    name: "Identity Master",
    description: "90%+ correct on Identity & Access (min 20 answered)",
    iconPath: "/badges/domain_master_identity.svg",
    xpReward: 200,
    rarity: "epic",
  },
  {
    key: "domain_master_networking",
    name: "Network Master",
    description: "90%+ correct on Secure Networking (min 20 answered)",
    iconPath: "/badges/domain_master_networking.svg",
    xpReward: 200,
    rarity: "epic",
  },
  {
    key: "domain_master_compute",
    name: "Compute Master",
    description: "90%+ correct on Compute, Storage & DB (min 20 answered)",
    iconPath: "/badges/domain_master_compute.svg",
    xpReward: 200,
    rarity: "epic",
  },
  {
    key: "domain_master_defender",
    name: "Defender Master",
    description: "90%+ correct on Defender & Sentinel (min 20 answered)",
    iconPath: "/badges/domain_master_defender.svg",
    xpReward: 200,
    rarity: "epic",
  },
  {
    key: "all_domains_mastered",
    name: "Azure Security God",
    description: "Earn all 4 Domain Master badges",
    iconPath: "/badges/all_domains_mastered.svg",
    xpReward: 500,
    rarity: "legendary",
  },
  {
    key: "boss_slayer",
    name: "Boss Slayer",
    description: "Complete a Boss Fight with 70% or higher",
    iconPath: "/badges/boss_slayer.svg",
    xpReward: 300,
    rarity: "rare",
  },
  {
    key: "perfect_boss",
    name: "Perfect Storm",
    description: "Complete a Boss Fight with 100%",
    iconPath: "/badges/perfect_boss.svg",
    xpReward: 750,
    rarity: "legendary",
  },
  {
    key: "streak_7",
    name: "Week Warrior",
    description: "Study 7 days in a row",
    iconPath: "/badges/streak_7.svg",
    xpReward: 150,
    rarity: "rare",
  },
  {
    key: "streak_30",
    name: "Monthly Dedication",
    description: "Study 30 days in a row",
    iconPath: "/badges/streak_30.svg",
    xpReward: 500,
    rarity: "legendary",
  },
  {
    key: "centurion",
    name: "Centurion",
    description: "Answer 100 questions total",
    iconPath: "/badges/centurion.svg",
    xpReward: 100,
    rarity: "rare",
  },
  {
    key: "completionist",
    name: "Completionist",
    description: "Answer at least one question from every topic",
    iconPath: "/badges/completionist.svg",
    xpReward: 250,
    rarity: "epic",
  },
  {
    key: "night_owl",
    name: "Night Owl",
    description: "Complete a study session between midnight and 5am",
    iconPath: "/badges/night_owl.svg",
    xpReward: 50,
    rarity: "common",
  },
  {
    key: "speed_run",
    name: "Speed Run",
    description: "Complete a Boss Fight in under 20 minutes",
    iconPath: "/badges/speed_run.svg",
    xpReward: 400,
    rarity: "epic",
  },
];

export function getAchievementByKey(key: string): AchievementDef | undefined {
  return ACHIEVEMENTS.find((a) => a.key === key);
}
